# Generated by Django 2.1.1 on 2019-12-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_main_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_message',
            old_name='message',
            new_name='big_message',
        ),
        migrations.AddField(
            model_name='main_message',
            name='d_day',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_message',
            name='d_day_message',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_message',
            name='low_message',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_message',
            name='middle_message',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
