# Generated by Django 2.1.1 on 2019-12-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191212_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_message',
            old_name='d_day',
            new_name='d_day_day',
        ),
        migrations.AddField(
            model_name='main_message',
            name='d_day_month',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_message',
            name='d_day_year',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
