# Generated by Django 2.1.1 on 2019-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Body', models.TextField(max_length=10)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Author', models.CharField(max_length=13)),
                ('Category', models.CharField(max_length=13)),
                ('HowMuch', models.IntegerField()),
            ],
        ),
    ]
