# Generated by Django 2.2.6 on 2019-10-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='Name',
            field=models.CharField(default=12, max_length=13),
            preserve_default=False,
        ),
    ]
