# Generated by Django 2.1.1 on 2019-10-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20191008_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='files',
            field=models.FileField(default=' ', upload_to='files/'),
        ),
    ]
