# Generated by Django 2.1.1 on 2019-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_hitcount_hittimecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='files',
            field=models.FileField(default='', upload_to='files/'),
        ),
    ]
