# Generated by Django 2.1.1 on 2019-11-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20191104_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='images',
            field=models.FileField(default='', upload_to='Sumnail/'),
        ),
    ]
