# Generated by Django 2.1.1 on 2019-11-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Name',
        ),
    ]
